# @package _global_

defaults:
  - /models@models.pretrained_flow: xxxs_flow_256
  - /models@models.kernel: direct_kernel
  - /dataset@dataset.train: bdd100k_synthetic_clean
  - /dataset@dataset.test: bdd100k_synthetic_clean
  - /loss@loss.aux: flow_matching
  - override /training: default
  - override /generation: flow

models:
  pretrained_flow:
    path: null
  kernel:
    kernel_size: 28
    padding: replicate
    sum_to_one: true
    learn_output_noise: false

optim:
  aux:
    lr: 0.00001
  kernel:
    lr: 0.00004

loss:
  name: di
  center_reg: 0.01
  sparse_reg: 0.01
  gaussian_reg: 0.1
  n_inner_steps: 1
  n_accum_steps: 1

training:
  batch_size: 32
  num_workers: 4
  max_val_batches: 0
  max_steps: ${parse_nimg:"1030Ki"}
  report_every_steps: ${parse_nimg:"16Ki"}
  plot_every_steps: ${parse_nimg:"128Ki"}
  save_every_steps: ${parse_nimg:"256Ki"}
  save_eval_to_file: false

exp_name: bdd100k_synthetic_step2
